"""
Canonical 19-Domain Question Bank Catalog for Student-Centric Intake Engine.
Per ONBOARDING_KNOWLEDGE_BASE.md and Design Decisions.
"""
from dataclasses import dataclass, field
from typing import Dict, List, Literal, Optional

TierType = Literal["T0", "T1", "T2"]
StoreType = Literal["user_profiles", "schedule_items", "tracker_definitions", "semantic_contexts"]


@dataclass(frozen=True)
class QuestionTopic:
    topic_id: str
    domain: str
    domain_code: str
    title: str
    tier: TierType
    prompt_question: str
    target_store: StoreType
    is_optional: bool = False
    dependencies: List[str] = field(default_factory=list)
    keywords: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# The Canonical Question Bank (A1 - S3)
# ---------------------------------------------------------------------------
QUESTION_BANK: Dict[str, QuestionTopic] = {
    # -----------------------------------------------------------------------
    # Identity (A)
    # -----------------------------------------------------------------------
    "A1": QuestionTopic(
        topic_id="A1",
        domain="Identity",
        domain_code="A",
        title="Name & Pronouns",
        tier="T0",
        prompt_question="What should I call you?",
        target_store="user_profiles",
        keywords=["name", "call me", "i am", "pronouns"],
    ),
    "A2": QuestionTopic(
        topic_id="A2",
        domain="Identity",
        domain_code="A",
        title="Program, Year & Semester",
        tier="T0",
        prompt_question="What program, year, and semester are you currently in (e.g., 3rd-sem CSE)?",
        target_store="user_profiles",
        keywords=["sem", "semester", "year", "branch", "cse", "ece", "btech", "degree", "program"],
    ),
    "A3": QuestionTopic(
        topic_id="A3",
        domain="Identity",
        domain_code="A",
        title="College / University",
        tier="T0",
        prompt_question="Which college or university are you attending?",
        target_store="user_profiles",
        keywords=["college", "university", "campus", "institute"],
    ),
    "A4": QuestionTopic(
        topic_id="A4",
        domain="Identity",
        domain_code="A",
        title="Living Situation",
        tier="T1",
        prompt_question="What's your living situation—are you in a hostel, flat, or living at home?",
        target_store="semantic_contexts",
        keywords=["hostel", "dorm", "pg", "flat", "apartment", "day scholar", "staying at home"],
    ),
    "A5": QuestionTopic(
        topic_id="A5",
        domain="Identity",
        domain_code="A",
        title="City & Timezone",
        tier="T2",
        prompt_question="Which city or timezone are you located in?",
        target_store="user_profiles",
        keywords=["city", "timezone", "location", "ist"],
    ),
    "A6": QuestionTopic(
        topic_id="A6",
        domain="Identity",
        domain_code="A",
        title="Commute Time & Mode",
        tier="T1",
        prompt_question="How long does your daily commute take, and how do you travel?",
        target_store="semantic_contexts",
        keywords=["commute", "travel time", "metro", "bus", "bike", "walk to college"],
    ),
    "A7": QuestionTopic(
        topic_id="A7",
        domain="Identity",
        domain_code="A",
        title="Hardware & Connectivity",
        tier="T2",
        prompt_question="What hardware and internet setup do you rely on for studying?",
        target_store="semantic_contexts",
        keywords=["laptop", "wifi", "macbook", "phone", "internet"],
    ),
    "A8": QuestionTopic(
        topic_id="A8",
        domain="Identity",
        domain_code="A",
        title="Languages",
        tier="T2",
        prompt_question="What languages do you prefer for communication and study resources?",
        target_store="semantic_contexts",
        keywords=["language", "english", "hindi", "kannada", "tamil"],
    ),

    # -----------------------------------------------------------------------
    # Courses (B)
    # -----------------------------------------------------------------------
    "B1": QuestionTopic(
        topic_id="B1",
        domain="Courses",
        domain_code="B",
        title="Course List",
        tier="T0",
        prompt_question="What subjects or courses are you taking this semester?",
        target_store="semantic_contexts",
        keywords=["courses", "subjects", "classes", "modules", "taking", "syllabus"],
    ),
    "B2": QuestionTopic(
        topic_id="B2",
        domain="Courses",
        domain_code="B",
        title="Theory vs Lab Split",
        tier="T1",
        prompt_question="Which of these courses have heavy lab or practical components versus pure theory?",
        target_store="semantic_contexts",
        dependencies=["B1"],
        keywords=["lab", "theory", "credits", "practical"],
    ),
    "B3": QuestionTopic(
        topic_id="B3",
        domain="Courses",
        domain_code="B",
        title="Professor Rules & Attendance Expectations",
        tier="T1",
        prompt_question="Are there strict professor rules or attendance expectations for any of these courses?",
        target_store="semantic_contexts",
        dependencies=["B1"],
        keywords=["professor", "attendance rule", "strict", "proxy", "roll call"],
    ),
    "B4": QuestionTopic(
        topic_id="B4",
        domain="Courses",
        domain_code="B",
        title="Syllabus & Slides Availability",
        tier="T1",
        prompt_question="Do you have the official syllabus copy, course handout, or slide deck PDFs for your courses? Uploading the PDF lets me parse the exact units and exam weightage directly, or you can just list key topics.",
        target_store="semantic_contexts",
        dependencies=["B1"],
        keywords=["syllabus pdf", "slides", "notes link", "drive link"],
    ),
    "B5": QuestionTopic(
        topic_id="B5",
        domain="Courses",
        domain_code="B",
        title="Easy vs Scary Subjects",
        tier="T1",
        prompt_question="Which subjects feel comfortable, and which ones feel intimidating or risky?",
        target_store="semantic_contexts",
        dependencies=["B1"],
        keywords=["scary", "hard", "tough", "easy", "comfortable", "dreading"],
    ),
    "B6": QuestionTopic(
        topic_id="B6",
        domain="Courses",
        domain_code="B",
        title="Weak Topics & Pain Points",
        tier="T1",
        prompt_question="Are there specific chapters or topics right now where you feel lost or behind?",
        target_store="semantic_contexts",
        dependencies=["B1"],
        keywords=["weak topic", "lost", "behind", "confusing", "flunking"],
    ),
    "B7": QuestionTopic(
        topic_id="B7",
        domain="Courses",
        domain_code="B",
        title="Backlogs / Arrears",
        tier="T2",
        prompt_question="Do you have any past backlogs or arrears you need to clear this term?",
        target_store="schedule_items",
        is_optional=True,
        keywords=["backlog", "arrear", "reappear", "repeat exam"],
    ),
    "B8": QuestionTopic(
        topic_id="B8",
        domain="Courses",
        domain_code="B",
        title="High-Priority Courses",
        tier="T1",
        prompt_question="If you had to pick the 1 or 2 courses that matter most to your GPA right now, which are they?",
        target_store="semantic_contexts",
        dependencies=["B1"],
        keywords=["high priority", "most important", "highest credit"],
    ),
    "B9": QuestionTopic(
        topic_id="B9",
        domain="Courses",
        domain_code="B",
        title="Core Textbooks & Video Channels",
        tier="T2",
        prompt_question="What are your go-to YouTube channels, textbooks, or notes sources?",
        target_store="semantic_contexts",
        keywords=["youtube channel", "textbook", "nptel", "gate smashers", "striver"],
    ),

    # -----------------------------------------------------------------------
    # Timetable (C)
    # -----------------------------------------------------------------------
    "C1": QuestionTopic(
        topic_id="C1",
        domain="Timetable",
        domain_code="C",
        title="Weekly Class & Lab Schedule",
        tier="T0",
        prompt_question="Do you have your official timetable PDF or a photo/screenshot of it? You can upload it directly, or just type out the times if that's easier.",
        target_store="schedule_items",
        keywords=["timetable", "class timing", "schedule", "lab time", "9 to 4", "fixed classes"],
    ),
    "C2": QuestionTopic(
        topic_id="C2",
        domain="Timetable",
        domain_code="C",
        title="Free Periods & Gaps",
        tier="T1",
        prompt_question="Do you have free periods or campus gaps during the week where you can get work done?",
        target_store="semantic_contexts",
        dependencies=["C1"],
        keywords=["free period", "gap", "break between classes", "free hour"],
    ),
    "C3": QuestionTopic(
        topic_id="C3",
        domain="Timetable",
        domain_code="C",
        title="Rotating Batches & Odd-Even Weeks",
        tier="T2",
        prompt_question="Do you have your official batch rotation schedule PDF or a photo of it? You can upload it directly, or just type out how your lab batches rotate.",
        target_store="schedule_items",
        dependencies=["C1"],
        keywords=["batch a", "batch b", "alternating week", "odd week", "even week"],
    ),
    "C4": QuestionTopic(
        topic_id="C4",
        domain="Timetable",
        domain_code="C",
        title="Meal & Break Times",
        tier="T1",
        prompt_question="When are your fixed meal and lunch break windows?",
        target_store="schedule_items",
        keywords=["lunch", "dinner", "breakfast", "mess time", "meal break"],
    ),
    "C5": QuestionTopic(
        topic_id="C5",
        domain="Timetable",
        domain_code="C",
        title="Mandatory Recurring Events",
        tier="T1",
        prompt_question="Are there recurring departmental meetings, seminars, or mandatory assemblies?",
        target_store="schedule_items",
        keywords=["department meeting", "seminar", "assembly", "mentor meeting"],
    ),

    # -----------------------------------------------------------------------
    # Assessments (D)
    # -----------------------------------------------------------------------
    "D1": QuestionTopic(
        topic_id="D1",
        domain="Assessments",
        domain_code="D",
        title="Next 3 Deadlines / Exams",
        tier="T0",
        prompt_question="If your department released an official exam timetable or circular PDF/image, upload it here so I can lock in the exact dates and slots without errors, or type out your next 1 to 3 imminent deadlines.",
        target_store="schedule_items",
        keywords=["exam", "test", "internal", "quiz", "deadline", "midterm", "viva", "submission"],
    ),
    "D2": QuestionTopic(
        topic_id="D2",
        domain="Assessments",
        domain_code="D",
        title="Internals / Midterms Schedule",
        tier="T1",
        prompt_question="If your department released an official midterm timetable or circular PDF/image, upload it here so I can lock in the exact dates and slots without errors, or type out when your internals are scheduled.",
        target_store="schedule_items",
        keywords=["internals", "midterms", "cie", "first internal", "second internal"],
    ),
    "D3": QuestionTopic(
        topic_id="D3",
        domain="Assessments",
        domain_code="D",
        title="End-Sem Dates & Study Leaves",
        tier="T1",
        prompt_question="If your department released the official end-sem exam timetable or circular PDF/image, upload it here so I can lock in the exact dates and slots without errors, or type out when your finals begin.",
        target_store="schedule_items",
        keywords=["end sem", "finals", "semester exam", "study leave", "prep leave"],
    ),
    "D4": QuestionTopic(
        topic_id="D4",
        domain="Assessments",
        domain_code="D",
        title="Lab Vivas & Records Submission",
        tier="T1",
        prompt_question="When are lab records due, and how frequent are lab vivas?",
        target_store="schedule_items",
        keywords=["lab record", "viva", "lab exam", "practical exam", "observation book"],
    ),
    "D5": QuestionTopic(
        topic_id="D5",
        domain="Assessments",
        domain_code="D",
        title="Assignments & Course Projects",
        tier="T1",
        prompt_question="What assignments or semester projects are due in the next few weeks?",
        target_store="schedule_items",
        keywords=["assignment", "mini project", "term paper", "report"],
    ),
    "D6": QuestionTopic(
        topic_id="D6",
        domain="Assessments",
        domain_code="D",
        title="Grading Weightages & Relative Curves",
        tier="T2",
        prompt_question="How is grading split between internals and finals, and is there relative grading?",
        target_store="semantic_contexts",
        keywords=["grading", "weightage", "relative grading", "50-50", "curve"],
    ),
    "D7": QuestionTopic(
        topic_id="D7",
        domain="Assessments",
        domain_code="D",
        title="Target CGPA / Minimum Grade",
        tier="T1",
        prompt_question="What is your target GPA/CGPA for this semester?",
        target_store="user_profiles",
        keywords=["target cgpa", "gpa goal", "8.5", "9.0", "target grade"],
    ),
    "D8": QuestionTopic(
        topic_id="D8",
        domain="Assessments",
        domain_code="D",
        title="Attendance Cutoffs",
        tier="T1",
        prompt_question="What is your university's attendance threshold (e.g. 75% or 85%)?",
        target_store="semantic_contexts",
        keywords=["attendance cutoff", "75%", "85%", "detention", "medical certificate"],
    ),
    "D9": QuestionTopic(
        topic_id="D9",
        domain="Assessments",
        domain_code="D",
        title="Exam Prep Style & Lead Time",
        tier="T2",
        prompt_question="Do you prefer studying weeks in advance, or do you thrive on intense 3-day sprints?",
        target_store="semantic_contexts",
        keywords=["cramming", "lead time", "sprint", "advance study", "revision cadence"],
    ),

    # -----------------------------------------------------------------------
    # Study Habits (E)
    # -----------------------------------------------------------------------
    "E1": QuestionTopic(
        topic_id="E1",
        domain="Study Habits",
        domain_code="E",
        title="Peak Focus Window",
        tier="T1",
        prompt_question="When is your brain at its sharpest—early morning, afternoon, or late night?",
        target_store="semantic_contexts",
        keywords=["peak focus", "morning person", "night owl", "sharpest", "best study hour"],
    ),
    "E2": QuestionTopic(
        topic_id="E2",
        domain="Study Habits",
        domain_code="E",
        title="Max Focus Span",
        tier="T1",
        prompt_question="How long can you focus before your attention drops (e.g. 30, 45, or 60 minutes)?",
        target_store="semantic_contexts",
        keywords=["focus span", "pomodoro", "attention span", "45 min", "1 hour focus"],
    ),
    "E3": QuestionTopic(
        topic_id="E3",
        domain="Study Habits",
        domain_code="E",
        title="Study Environment",
        tier="T2",
        prompt_question="Where do you get your best work done—library, bedroom desk, or noisy cafe?",
        target_store="semantic_contexts",
        keywords=["library", "study spot", "desk", "cafe", "noise"],
    ),
    "E4": QuestionTopic(
        topic_id="E4",
        domain="Study Habits",
        domain_code="E",
        title="Derail Triggers",
        tier="T1",
        prompt_question="What usually derails your study sessions—phone notifications, friends dropping in, or tiredness?",
        target_store="semantic_contexts",
        keywords=["derail", "distraction", "phone", "reels", "friends", "fatigue"],
    ),
    "E5": QuestionTopic(
        topic_id="E5",
        domain="Study Habits",
        domain_code="E",
        title="Study Methods",
        tier="T2",
        prompt_question="How do you study best—solving problems, making summary sheets, or active recall?",
        target_store="semantic_contexts",
        keywords=["active recall", "practice problems", "summary", "flashcards", "past papers"],
    ),
    "E6": QuestionTopic(
        topic_id="E6",
        domain="Study Habits",
        domain_code="E",
        title="Max Daily Study Cap",
        tier="T1",
        prompt_question="What is the realistic maximum number of self-study hours you can sustain in a single day?",
        target_store="user_profiles",
        keywords=["max study hours", "daily cap", "burnout ceiling", "6 hours", "8 hours"],
    ),
    "E7": QuestionTopic(
        topic_id="E7",
        domain="Study Habits",
        domain_code="E",
        title="Hard Time / Day Cutoffs",
        tier="T0",
        prompt_question="Are there hard boundaries when you refuse to study (e.g., no screen work past 10 PM, Sundays off)?",
        target_store="semantic_contexts",
        keywords=["no study past", "hard cutoff", "sunday off", "curfew", "screen cutoff", "migraine cutoff"],
    ),

    # -----------------------------------------------------------------------
    # Goals & Career (F)
    # -----------------------------------------------------------------------
    "F1": QuestionTopic(
        topic_id="F1",
        domain="Goals & Career",
        domain_code="F",
        title="Top 1–3 Goals This Semester",
        tier="T0",
        prompt_question="What are your top 1 to 3 primary goals for this semester?",
        target_store="schedule_items",
        keywords=["top goal", "semester goal", "aim", "target", "priority this term"],
    ),
    "F2": QuestionTopic(
        topic_id="F2",
        domain="Goals & Career",
        domain_code="F",
        title="Post-College Path",
        tier="T1",
        prompt_question="What direction are you aiming for after graduation—campus placements, MS/PhD, GATE, or startups?",
        target_store="semantic_contexts",
        keywords=["placements", "higher studies", "gate", "gre", "cat", "startup", "career"],
    ),
    "F3": QuestionTopic(
        topic_id="F3",
        domain="Goals & Career",
        domain_code="F",
        title="Target Companies & Exams",
        tier="T2",
        prompt_question="Are there specific target companies, competitive exams, or cutoffs on your radar?",
        target_store="semantic_contexts",
        keywords=["target company", "faang", "google", "gate 2027", "placement test"],
    ),
    "F4": QuestionTopic(
        topic_id="F4",
        domain="Goals & Career",
        domain_code="F",
        title="Skill Priorities",
        tier="T1",
        prompt_question="What specific technical skills or domains are you trying to build (e.g. LeetCode DSA, AI/ML, Full-Stack)?",
        target_store="semantic_contexts",
        keywords=["dsa", "leetcode", "web dev", "ai/ml", "system design", "skills"],
    ),
    "F5": QuestionTopic(
        topic_id="F5",
        domain="Goals & Career",
        domain_code="F",
        title="Competitive Programming & Hackathons",
        tier="T2",
        prompt_question="Do you participate in code contests, Codeforces, or hackathons?",
        target_store="semantic_contexts",
        keywords=["codeforces", "codechef", "hackathon", "cp", "contests"],
    ),
    "F6": QuestionTopic(
        topic_id="F6",
        domain="Goals & Career",
        domain_code="F",
        title="Personal Projects & Portfolio",
        tier="T1",
        prompt_question="Are you building any personal projects, portfolio apps, or open-source tools?",
        target_store="schedule_items",
        keywords=["personal project", "portfolio", "github", "side project", "open source"],
    ),
    "F7": QuestionTopic(
        topic_id="F7",
        domain="Goals & Career",
        domain_code="F",
        title="Internship Timeline",
        tier="T1",
        prompt_question="When is your internship hiring season or application window?",
        target_store="schedule_items",
        keywords=["internship", "intern season", "referrals", "oa season"],
    ),
    "F8": QuestionTopic(
        topic_id="F8",
        domain="Goals & Career",
        domain_code="F",
        title="Semester Success Metric",
        tier="T2",
        prompt_question="How will you measure if this semester was a clear win at the end of it?",
        target_store="semantic_contexts",
        keywords=["success metric", "win", "satisfaction", "criteria"],
    ),
    "F9": QuestionTopic(
        topic_id="F9",
        domain="Goals & Career",
        domain_code="F",
        title="Chronic Procrastinations",
        tier="T2",
        prompt_question="What is the one task or responsibility you chronically put off until the last minute?",
        target_store="semantic_contexts",
        keywords=["procrastinate", "avoid", "put off", "dread doing"],
    ),

    # -----------------------------------------------------------------------
    # Clubs & Extra (G)
    # -----------------------------------------------------------------------
    "G1": QuestionTopic(
        topic_id="G1",
        domain="Clubs & Extra",
        domain_code="G",
        title="Active Clubs & Societies",
        tier="T1",
        prompt_question="Are you involved in any college clubs, student societies, or sports teams?",
        target_store="semantic_contexts",
        keywords=["club", "society", "ieee", "rotaract", "gdsc", "dance team"],
    ),
    "G2": QuestionTopic(
        topic_id="G2",
        domain="Clubs & Extra",
        domain_code="G",
        title="Club Role & Hours Committed",
        tier="T1",
        prompt_question="What is your role in these clubs, and roughly how many hours per week do you commit?",
        target_store="semantic_contexts",
        dependencies=["G1"],
        keywords=["lead", "core committee", "volunteer", "club hours"],
    ),
    "G3": QuestionTopic(
        topic_id="G3",
        domain="Clubs & Extra",
        domain_code="G",
        title="Regular Meeting Slots",
        tier="T1",
        prompt_question="When are the fixed club meetings, rehearsals, or team standups?",
        target_store="schedule_items",
        dependencies=["G1"],
        keywords=["club meeting", "rehearsal", "standup", "team slot"],
    ),
    "G4": QuestionTopic(
        topic_id="G4",
        domain="Clubs & Extra",
        domain_code="G",
        title="Upcoming College Fests",
        tier="T1",
        prompt_question="Is there an upcoming college fest or major event that will demand your time?",
        target_store="schedule_items",
        keywords=["college fest", "cultural fest", "tech fest", "organizing"],
    ),
    "G5": QuestionTopic(
        topic_id="G5",
        domain="Clubs & Extra",
        domain_code="G",
        title="Deliverables & Responsibilities",
        tier="T2",
        prompt_question="Do you have specific club deliverables like posters, logistics, or code?",
        target_store="schedule_items",
        dependencies=["G1"],
        keywords=["deliverables", "posters", "social media", "logistics"],
    ),
    "G6": QuestionTopic(
        topic_id="G6",
        domain="Clubs & Extra",
        domain_code="G",
        title="Clubs to Join / Quit",
        tier="T2",
        prompt_question="Are there any clubs you are planning to quit or audition for soon?",
        target_store="semantic_contexts",
        keywords=["quit club", "join club", "audition", "step down"],
    ),

    # -----------------------------------------------------------------------
    # Hobbies (H)
    # -----------------------------------------------------------------------
    "H1": QuestionTopic(
        topic_id="H1",
        domain="Hobbies",
        domain_code="H",
        title="Casual Fun & Decompression",
        tier="T1",
        prompt_question="What do you do just to unwind and decompress when you have free time?",
        target_store="semantic_contexts",
        keywords=["relax", "unwind", "fun", "gaming", "shows", "read fiction"],
    ),
    "H2": QuestionTopic(
        topic_id="H2",
        domain="Hobbies",
        domain_code="H",
        title="Protected Hobbies",
        tier="T1",
        prompt_question="Are there hobbies you consider non-negotiable and refuse to sacrifice (e.g. gym, guitar)?",
        target_store="schedule_items",
        keywords=["protected hobby", "non negotiable fun", "music", "guitar", "gaming time"],
    ),
    "H3": QuestionTopic(
        topic_id="H3",
        domain="Hobbies",
        domain_code="H",
        title="Hobbies to Start",
        tier="T2",
        prompt_question="Is there an activity or creative hobby you've been wishing you had time for?",
        target_store="semantic_contexts",
        keywords=["want to start", "new hobby", "creative", "wish i could"],
    ),
    "H4": QuestionTopic(
        topic_id="H4",
        domain="Hobbies",
        domain_code="H",
        title="Weekly Frequency & Duration",
        tier="T1",
        prompt_question="How many sessions a week do you want set aside for this?",
        target_store="semantic_contexts",
        keywords=["frequency", "how many days", "session length"],
    ),
    "H5": QuestionTopic(
        topic_id="H5",
        domain="Hobbies",
        domain_code="H",
        title="Metrics Tracked",
        tier="T1",
        prompt_question="Do you track any metrics for your hobbies (e.g., pages read, drawing daily)?",
        target_store="tracker_definitions",
        keywords=["pages read", "hobby tracker", "reading log"],
    ),
    "H6": QuestionTopic(
        topic_id="H6",
        domain="Hobbies",
        domain_code="H",
        title="Screen Leisure Limits",
        tier="T2",
        prompt_question="Do you want to cap your recreational screen time or binge-watching?",
        target_store="semantic_contexts",
        keywords=["screen limit", "binge", "netflix limit", "youtube limit"],
    ),

    # -----------------------------------------------------------------------
    # Social (I)
    # -----------------------------------------------------------------------
    "I1": QuestionTopic(
        topic_id="I1",
        domain="Social",
        domain_code="I",
        title="Key Friend Circles",
        tier="T1",
        prompt_question="Who are your primary friends or study buddies on campus?",
        target_store="semantic_contexts",
        keywords=["friends", "group", "roommates", "study buddies"],
    ),
    "I2": QuestionTopic(
        topic_id="I2",
        domain="Social",
        domain_code="I",
        title="Desired Social Frequency",
        tier="T1",
        prompt_question="How often do you like hanging out—daily tea breaks, or just weekend evenings?",
        target_store="semantic_contexts",
        keywords=["hangout", "chai break", "weekend social", "social frequency"],
    ),
    "I3": QuestionTopic(
        topic_id="I3",
        domain="Social",
        domain_code="I",
        title="Calls / Trips Home",
        tier="T1",
        prompt_question="When do you usually call family or visit home?",
        target_store="schedule_items",
        keywords=["call mom", "call parents", "family call", "visit home"],
    ),
    "I4": QuestionTopic(
        topic_id="I4",
        domain="Social",
        domain_code="I",
        title="Recurring Social Blocks",
        tier="T2",
        prompt_question="Do you have fixed social plans like Friday board games or Sunday dinners?",
        target_store="schedule_items",
        keywords=["friday night", "outing", "dinner with friends", "party"],
    ),
    "I5": QuestionTopic(
        topic_id="I5",
        domain="Social",
        domain_code="I",
        title="Upcoming Trips / Events",
        tier="T1",
        prompt_question="Are there upcoming birthdays, weddings, or weekend trips on your calendar?",
        target_store="schedule_items",
        keywords=["trip", "birthday", "wedding", "travel weekend"],
    ),
    "I6": QuestionTopic(
        topic_id="I6",
        domain="Social",
        domain_code="I",
        title="Relationships",
        tier="T2",
        prompt_question="Do you have protected date nights or partner time you want blocked off?",
        target_store="semantic_contexts",
        is_optional=True,
        keywords=["relationship", "partner", "date night"],
    ),
    "I7": QuestionTopic(
        topic_id="I7",
        domain="Social",
        domain_code="I",
        title="Social Balance & Energy",
        tier="T2",
        prompt_question="Does excessive socializing drain your focus, or recharge you?",
        target_store="semantic_contexts",
        keywords=["introvert", "extrovert", "social battery", "drain"],
    ),

    # -----------------------------------------------------------------------
    # Fitness & Food (J)
    # -----------------------------------------------------------------------
    "J1": QuestionTopic(
        topic_id="J1",
        domain="Fitness & Food",
        domain_code="J",
        title="Current Workout Routine",
        tier="T1",
        prompt_question="What does your current fitness routine look like (e.g. gym, running, badminton, none)?",
        target_store="schedule_items",
        keywords=["gym", "workout", "exercise", "running", "sports", "badminton"],
    ),
    "J2": QuestionTopic(
        topic_id="J2",
        domain="Fitness & Food",
        domain_code="J",
        title="Fitness Targets",
        tier="T1",
        prompt_question="What are your fitness targets (e.g. hypertrophy, endurance, weight management)?",
        target_store="tracker_definitions",
        keywords=["weight loss", "muscle gain", "stamina", "run 5k"],
    ),
    "J3": QuestionTopic(
        topic_id="J3",
        domain="Fitness & Food",
        domain_code="J",
        title="Workout Location & Fixed Slots",
        tier="T1",
        prompt_question="Where and when do you prefer working out (e.g. college gym at 6 PM)?",
        target_store="schedule_items",
        keywords=["gym timing", "workout slot", "6 pm gym", "morning run"],
    ),
    "J4": QuestionTopic(
        topic_id="J4",
        domain="Fitness & Food",
        domain_code="J",
        title="Food Routine & Fixed Meals",
        tier="T1",
        prompt_question="What are your meal timings, and do you eat at a hostel mess or cook?",
        target_store="schedule_items",
        keywords=["mess food", "canteen", "cooking", "meal timing"],
    ),
    "J5": QuestionTopic(
        topic_id="J5",
        domain="Fitness & Food",
        domain_code="J",
        title="Dietary Rules & Fasts",
        tier="T1",
        prompt_question="Do you observe fasting days or specific dietary constraints?",
        target_store="semantic_contexts",
        keywords=["fasting", "dietary restriction", "vegetarian", "ekadashi", "ramadan"],
    ),
    "J6": QuestionTopic(
        topic_id="J6",
        domain="Fitness & Food",
        domain_code="J",
        title="Nutrition & Water Tracking",
        tier="T1",
        prompt_question="Do you want to log water intake, calories, or protein in your daily Rapid Log?",
        target_store="tracker_definitions",
        keywords=["water intake", "protein", "calories", "nutrition tracker"],
    ),
    "J7": QuestionTopic(
        topic_id="J7",
        domain="Fitness & Food",
        domain_code="J",
        title="Body & Energy Limits",
        tier="T2",
        prompt_question="Are there any physical injuries or health conditions that impact your schedule?",
        target_store="semantic_contexts",
        is_optional=True,
        keywords=["injury", "back pain", "health issue", "fatigue"],
    ),

    # -----------------------------------------------------------------------
    # Sleep & Energy (K)
    # -----------------------------------------------------------------------
    "K1": QuestionTopic(
        topic_id="K1",
        domain="Sleep & Energy",
        domain_code="K",
        title="Typical Sleep / Wake Window",
        tier="T0",
        prompt_question="What time do you usually go to bed and wake up on weekdays?",
        target_store="user_profiles",
        keywords=["sleep", "wake up", "bedtime", "wake time", "11 pm to 7 am", "sleep window"],
    ),
    "K2": QuestionTopic(
        topic_id="K2",
        domain="Sleep & Energy",
        domain_code="K",
        title="Weekend Sleep Shifts",
        tier="T1",
        prompt_question="Do you sleep in on weekends, or keep your schedule consistent?",
        target_store="semantic_contexts",
        keywords=["weekend sleep", "sleep in", "saturday night sleep"],
    ),
    "K3": QuestionTopic(
        topic_id="K3",
        domain="Sleep & Energy",
        domain_code="K",
        title="Peak vs Crash Hours",
        tier="T1",
        prompt_question="When do you feel energy slumps (like the post-lunch 2 PM dip)?",
        target_store="semantic_contexts",
        keywords=["afternoon slump", "crash hour", "energy dip", "sleepy afternoon"],
    ),
    "K4": QuestionTopic(
        topic_id="K4",
        domain="Sleep & Energy",
        domain_code="K",
        title="Naps",
        tier="T1",
        prompt_question="Do you take afternoon power naps, and for how long?",
        target_store="schedule_items",
        keywords=["nap", "power nap", "afternoon sleep", "20 min nap"],
    ),
    "K5": QuestionTopic(
        topic_id="K5",
        domain="Sleep & Energy",
        domain_code="K",
        title="Caffeine & All-Nighter Tolerance",
        tier="T2",
        prompt_question="How is your caffeine intake, and do you ever pull all-nighters before exams?",
        target_store="semantic_contexts",
        is_optional=True,
        keywords=["caffeine", "coffee", "tea", "all-nighter", "red bull"],
    ),
    "K6": QuestionTopic(
        topic_id="K6",
        domain="Sleep & Energy",
        domain_code="K",
        title="Bedtime Goals",
        tier="T1",
        prompt_question="What is your ideal bedtime target that you want help sticking to?",
        target_store="user_profiles",
        keywords=["target bedtime", "fix sleep", "sleep earlier"],
    ),
    "K7": QuestionTopic(
        topic_id="K7",
        domain="Sleep & Energy",
        domain_code="K",
        title="Sleep Trackers",
        tier="T2",
        prompt_question="Do you use a smart watch or sleep tracker app?",
        target_store="semantic_contexts",
        keywords=["apple watch", "whoop", "fitbit", "sleep app"],
    ),

    # -----------------------------------------------------------------------
    # Wellbeing (L)
    # -----------------------------------------------------------------------
    "L1": QuestionTopic(
        topic_id="L1",
        domain="Wellbeing",
        domain_code="L",
        title="Top Stressor",
        tier="T1",
        prompt_question="What is the single biggest thing causing you stress or mental weight right now?",
        target_store="semantic_contexts",
        keywords=["stress", "anxious", "worried", "mental weight", "overwhelmed by"],
    ),
    "L2": QuestionTopic(
        topic_id="L2",
        domain="Wellbeing",
        domain_code="L",
        title="Overwhelm Triggers",
        tier="T1",
        prompt_question="What specific situations trigger overwhelm for you (e.g. piled-up assignments)?",
        target_store="semantic_contexts",
        keywords=["overwhelm trigger", "panic", "paralysis", "too much work"],
    ),
    "L3": QuestionTopic(
        topic_id="L3",
        domain="Wellbeing",
        domain_code="L",
        title="Recovery Anchors",
        tier="T1",
        prompt_question="What helps you reset when you're overwhelmed—a walk, music, calling home, or quiet time?",
        target_store="semantic_contexts",
        keywords=["recovery", "reset", "calm down", "walk", "anchor"],
    ),
    "L4": QuestionTopic(
        topic_id="L4",
        domain="Wellbeing",
        domain_code="L",
        title="Daily Mood Check-Ins",
        tier="T2",
        prompt_question="Would you like a quick 1–10 stress check-in during your daily logs?",
        target_store="tracker_definitions",
        keywords=["mood check", "stress /10", "daily rating"],
    ),
    "L5": QuestionTopic(
        topic_id="L5",
        domain="Wellbeing",
        domain_code="L",
        title="Journaling & Meditation",
        tier="T2",
        prompt_question="Do you maintain a reflection journal or meditation practice?",
        target_store="semantic_contexts",
        keywords=["journal", "meditation", "mindfulness", "gratitude"],
    ),
    "L6": QuestionTopic(
        topic_id="L6",
        domain="Wellbeing",
        domain_code="L",
        title="System Support Behavior When Stressed",
        tier="T1",
        prompt_question="When you're overwhelmed, should I push you gently with small wins, or strip your schedule to the essentials?",
        target_store="semantic_contexts",
        keywords=["gentle support", "strip schedule", "support style", "crisis mode"],
    ),

    # -----------------------------------------------------------------------
    # Money (M - all optional)
    # -----------------------------------------------------------------------
    "M1": QuestionTopic(
        topic_id="M1",
        domain="Money",
        domain_code="M",
        title="Budget Tracking",
        tier="T2",
        prompt_question="Do you want to log daily expenses or track a monthly student budget?",
        target_store="tracker_definitions",
        is_optional=True,
        keywords=["budget", "expenses", "spending", "money"],
    ),
    "M2": QuestionTopic(
        topic_id="M2",
        domain="Money",
        domain_code="M",
        title="Expense Focus",
        tier="T2",
        prompt_question="Where does most of your discretionary money go—food, books, or travel?",
        target_store="semantic_contexts",
        is_optional=True,
        keywords=["food expense", "canteen money", "travel cost"],
    ),
    "M3": QuestionTopic(
        topic_id="M3",
        domain="Money",
        domain_code="M",
        title="Recurring Bills & Dues",
        tier="T2",
        prompt_question="Are there monthly PG rent, mess fees, or subscriptions due on fixed dates?",
        target_store="schedule_items",
        is_optional=True,
        keywords=["rent due", "mess fees", "subscription date"],
    ),
    "M4": QuestionTopic(
        topic_id="M4",
        domain="Money",
        domain_code="M",
        title="Savings Goals",
        tier="T2",
        prompt_question="Are you saving for anything in particular (e.g. a new laptop or exam fees)?",
        target_store="semantic_contexts",
        is_optional=True,
        keywords=["savings goal", "saving for laptop"],
    ),

    # -----------------------------------------------------------------------
    # Work & Internships (N)
    # -----------------------------------------------------------------------
    "N1": QuestionTopic(
        topic_id="N1",
        domain="Work & Internships",
        domain_code="N",
        title="Paid Work & Freelancing",
        tier="T1",
        prompt_question="Do you do any part-time work, freelancing, or teaching assistantships?",
        target_store="semantic_contexts",
        keywords=["freelance", "part-time job", "ta", "teaching assistant", "contract"],
    ),
    "N2": QuestionTopic(
        topic_id="N2",
        domain="Work & Internships",
        domain_code="N",
        title="Work Hours & Shifts",
        tier="T1",
        prompt_question="What are your fixed work hours or client meeting commitments?",
        target_store="schedule_items",
        dependencies=["N1"],
        keywords=["work shift", "client call", "shift timing", "work hours"],
    ),
    "N3": QuestionTopic(
        topic_id="N3",
        domain="Work & Internships",
        domain_code="N",
        title="Side Project Allocation",
        tier="T1",
        prompt_question="How many hours a week do you want reserved for your freelance or side work?",
        target_store="semantic_contexts",
        dependencies=["N1"],
        keywords=["freelance hours", "side project time"],
    ),
    "N4": QuestionTopic(
        topic_id="N4",
        domain="Work & Internships",
        domain_code="N",
        title="Internship Applications & Interviews",
        tier="T1",
        prompt_question="Do you have upcoming interview rounds or daily application quotas?",
        target_store="schedule_items",
        keywords=["interview round", "coding test", "oa", "application quota"],
    ),

    # -----------------------------------------------------------------------
    # Chores & Admin (O)
    # -----------------------------------------------------------------------
    "O1": QuestionTopic(
        topic_id="O1",
        domain="Chores & Admin",
        domain_code="O",
        title="Laundry & Room Chores",
        tier="T1",
        prompt_question="When do you usually do laundry, room cleaning, and grocery runs?",
        target_store="schedule_items",
        keywords=["laundry", "room cleaning", "chores", "grocery"],
    ),
    "O2": QuestionTopic(
        topic_id="O2",
        domain="Chores & Admin",
        domain_code="O",
        title="Academic Paperwork & Fee Deadlines",
        tier="T2",
        prompt_question="Do you have official circulars, fee notifications, or academic calendar PDFs/photos for upcoming deadlines? You can upload them directly, or just type out the dates.",
        target_store="schedule_items",
        keywords=["fee payment", "scholarship", "hall ticket", "paperwork"],
    ),
    "O3": QuestionTopic(
        topic_id="O3",
        domain="Chores & Admin",
        domain_code="O",
        title="Appointments",
        tier="T2",
        prompt_question="Any doctor, dentist, or personal appointments coming up?",
        target_store="schedule_items",
        keywords=["doctor appointment", "dentist", "medical checkup"],
    ),
    "O4": QuestionTopic(
        topic_id="O4",
        domain="Chores & Admin",
        domain_code="O",
        title="Recurring Items Forgotten",
        tier="T2",
        prompt_question="What life maintenance task do you constantly forget until it's an emergency?",
        target_store="semantic_contexts",
        keywords=["forget to do", "maintenance", "refill water"],
    ),

    # -----------------------------------------------------------------------
    # Digital Distractions (P)
    # -----------------------------------------------------------------------
    "P1": QuestionTopic(
        topic_id="P1",
        domain="Digital Distractions",
        domain_code="P",
        title="Phone / PC Time Sinks",
        tier="T1",
        prompt_question="What apps or sites are your biggest digital time-vampires (Instagram, YouTube, Discord, Twitter)?",
        target_store="semantic_contexts",
        keywords=["instagram", "reels", "shorts", "youtube rabbit hole", "discord", "twitter", "time sink"],
    ),
    "P2": QuestionTopic(
        topic_id="P2",
        domain="Digital Distractions",
        domain_code="P",
        title="Screen Time Caps",
        tier="T1",
        prompt_question="What screen time limit would you feel proud of hitting each day?",
        target_store="tracker_definitions",
        keywords=["screen time cap", "phone limit", "under 4 hours"],
    ),
    "P3": QuestionTopic(
        topic_id="P3",
        domain="Digital Distractions",
        domain_code="P",
        title="App / Site Restrictions During Work",
        tier="T2",
        prompt_question="Do you use website blockers like Forest, Freedom, or Opal?",
        target_store="semantic_contexts",
        keywords=["forest app", "freedom", "blocker", "dnd"],
    ),
    "P4": QuestionTopic(
        topic_id="P4",
        domain="Digital Distractions",
        domain_code="P",
        title="Distraction Hot Zones",
        tier="T1",
        prompt_question="When is your danger zone for doom-scrolling (e.g. right before bed, or waking up in bed)?",
        target_store="semantic_contexts",
        keywords=["doomscrolling", "bed scrolling", "late night scrolling", "morning scroll"],
    ),

    # -----------------------------------------------------------------------
    # Travel & Shifts (Q)
    # -----------------------------------------------------------------------
    "Q1": QuestionTopic(
        topic_id="Q1",
        domain="Travel & Shifts",
        domain_code="Q",
        title="Travel Home Frequency",
        tier="T1",
        prompt_question="How often do you travel back home (every weekend, once a month, only for breaks)?",
        target_store="semantic_contexts",
        keywords=["travel home", "visit parents", "monthly trip"],
    ),
    "Q2": QuestionTopic(
        topic_id="Q2",
        domain="Travel & Shifts",
        domain_code="Q",
        title="Upcoming Holidays & Festivals",
        tier="T1",
        prompt_question="Are there upcoming holidays or festivals where you plan to disconnect?",
        target_store="schedule_items",
        keywords=["diwali", "puja", "eid", "christmas", "holidays", "long weekend"],
    ),
    "Q3": QuestionTopic(
        topic_id="Q3",
        domain="Travel & Shifts",
        domain_code="Q",
        title="Atypical Weeks",
        tier="T1",
        prompt_question="Do your weeks dramatically shift between exam weeks and regular weeks?",
        target_store="semantic_contexts",
        keywords=["atypical week", "exam week routine", "fest week"],
    ),
    "Q4": QuestionTopic(
        topic_id="Q4",
        domain="Travel & Shifts",
        domain_code="Q",
        title="Cultural & Faith Commitments",
        tier="T2",
        prompt_question="Do you have weekly prayers or religious commitments you want reserved?",
        target_store="schedule_items",
        is_optional=True,
        keywords=["prayer time", "church", "temple", "friday prayer", "cultural"],
    ),

    # -----------------------------------------------------------------------
    # Working Preferences (R)
    # -----------------------------------------------------------------------
    "R1": QuestionTopic(
        topic_id="R1",
        domain="Working Preferences",
        domain_code="R",
        title="Tone: Gentle vs Blunt",
        tier="T1",
        prompt_question="How should I hold you accountable—gentle encouragement or blunt, no-nonsense truth?",
        target_store="semantic_contexts",
        keywords=["blunt", "gentle", "strict", "drill sergeant", "supportive"],
    ),
    "R2": QuestionTopic(
        topic_id="R2",
        domain="Working Preferences",
        domain_code="R",
        title="Check-In Cadence",
        tier="T1",
        prompt_question="How frequently do you want check-ins (morning briefing, evening debrief, or per-block)?",
        target_store="semantic_contexts",
        keywords=["morning check-in", "evening debrief", "cadence"],
    ),
    "R3": QuestionTopic(
        topic_id="R3",
        domain="Working Preferences",
        domain_code="R",
        title="Voice vs Typing",
        tier="T2",
        prompt_question="Do you prefer talking to me with your voice mic or typing short quick texts?",
        target_store="semantic_contexts",
        keywords=["voice input", "voice mic", "typing only"],
    ),
    "R4": QuestionTopic(
        topic_id="R4",
        domain="Working Preferences",
        domain_code="R",
        title="Audio Cues & Sound Feedback",
        tier="T2",
        prompt_question="Do you like playful audio cues (like success chimes and sad trombone) or total silence?",
        target_store="semantic_contexts",
        keywords=["sound effects", "audio cues", "jingle", "mute sounds"],
    ),
    "R5": QuestionTopic(
        topic_id="R5",
        domain="Working Preferences",
        domain_code="R",
        title="Off-Limits Topics & Hours",
        tier="T1",
        prompt_question="Are there any subjects or times that are strictly off-limits?",
        target_store="semantic_contexts",
        keywords=["off limits", "do not ask about", "private"],
    ),
    "R6": QuestionTopic(
        topic_id="R6",
        domain="Working Preferences",
        domain_code="R",
        title="Past Planning Failures",
        tier="T2",
        prompt_question="Why did your past calendars or Notion planners fail?",
        target_store="semantic_contexts",
        keywords=["notion failed", "google calendar abandoned", "planning failure"],
    ),

    # -----------------------------------------------------------------------
    # Closing (S)
    # -----------------------------------------------------------------------
    "S1": QuestionTopic(
        topic_id="S1",
        domain="Closing",
        domain_code="S",
        title="Ideal Week Vision",
        tier="T1",
        prompt_question="In one sentence, what does a completely victorious, unstressed week look like for you?",
        target_store="semantic_contexts",
        keywords=["ideal week", "victorious week", "dream schedule"],
    ),
    "S2": QuestionTopic(
        topic_id="S2",
        domain="Closing",
        domain_code="S",
        title="Primary Point of Failure to Fix",
        tier="T1",
        prompt_question="What is the single biggest habit breakdown or failure mode you want this system to prevent?",
        target_store="semantic_contexts",
        keywords=["failure mode", "breakdown", "fix this habit"],
    ),
    "S3": QuestionTopic(
        topic_id="S3",
        domain="Closing",
        domain_code="S",
        title="Open Catch-All",
        tier="T2",
        prompt_question="Is there anything else quirky or crucial about your life that I should know?",
        target_store="semantic_contexts",
        keywords=["anything else", "catch all", "quirk", "one more thing"],
    ),
}

# ---------------------------------------------------------------------------
# Strict Tier Constants
# ---------------------------------------------------------------------------
TIER_0_TOPICS: List[str] = [
    "A1",  # Name
    "A2",  # Program / Year / Sem
    "A3",  # College
    "B1",  # Course List
    "C1",  # Timetable (Class/Lab schedule)
    "D1",  # Next 3 Deadlines / Exams
    "E7",  # Hard Time / Day Cutoffs
    "F1",  # Top 1-3 Goals
    "K1",  # Typical Sleep/Wake Window
]

TIER_1_TOPICS: List[str] = [
    t_id for t_id, q in QUESTION_BANK.items() if q.tier == "T1"
]

TIER_2_TOPICS: List[str] = [
    t_id for t_id, q in QUESTION_BANK.items() if q.tier == "T2"
]


def get_question_by_id(topic_id: str) -> Optional[QuestionTopic]:
    return QUESTION_BANK.get(topic_id.upper())


def get_topics_by_tier(tier: TierType) -> List[QuestionTopic]:
    return [q for q in QUESTION_BANK.values() if q.tier == tier]
